### HEALTHCHECK
GET http://localhost:3000/healthcheck
Accept: application/json

### USER
### Register
POST http://localhost:3000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "username": "khilmi",
    "password": "khilmi1234",
    "name": "khilmi"
}


### Login
POST http://localhost:3000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "khilmi",
    "password": "khilmi1234"
}

### Logout
POST http://localhost:3000/api/v1/auth/logout
Accept: application/json
Content-Type: application/json
Authorization: 791b26c4-04a3-4e4a-928b-5f8111a3c869

### Get current user
GET http://localhost:3000/api/v1/users/current
Accept: application/json
Content-Type: application/json
Authorization: 791b26c4-04a3-4e4a-928b-5f8111a3c869

### UPDATE
PATCH  http://localhost:3000/api/v1/users/current
Accept: application/json
Content-Type: application/json
Authorization: 791b26c4-04a3-4e4a-928b-5f8111a3c869

{
    "name": "khilmi aminudin"
}


### CONTACT
### Create
POST http://localhost:3000/api/v1/contacts
Accept: application/json
Content-Type: application/json
Authorization: 791b26c4-04a3-4e4a-928b-5f8111a3c869

{
    "first_name": "khilmi",
    "last_name": "aminudin",
    "email": "khilmi@mail.com",
    "phone": "62099878687678"
}

### Get Contact
GET http://localhost:3000/api/v1/contacts/1
Accept: application/json
Content-Type: application/json
Authorization: 791b26c4-04a3-4e4a-928b-5f8111a3c869


### Update Contact
PUT  http://localhost:3000/api/v1/contacts/1sfdsdf
Accept: application/json
Content-Type: application/json
Authorization: 791b26c4-04a3-4e4a-928b-5f8111a3c869

{
    "first_name": "Akeno",
    "last_name": "Zahran Asadel",
    "email": "akeno@mail.com",
    "phone": "6209090909090"
}

### Delete Contact
DELETE  http://localhost:3000/api/v1/contacts/sds
Accept: application/json
Content-Type: application/json
Authorization: 791b26c4-04a3-4e4a-928b-5f8111a3c869

